import type { Locale } from '../../app/i18n';
const zh = {
  title: '重复照片', description: '按用户分别查找副本，对比后保留喜欢的照片。',
  exact: '完全重复', perceptual: '视觉相似', ai: 'AI 相似', refresh: '刷新', more: '加载更多',
  empty: '没有发现重复或相似照片。', scanning: '扫描视觉相似', scanAI: '扫描 AI 相似',
  scanNote: '完全重复无需扫描。视觉和 AI 扫描会保存特征，下次跳过未变化的照片。',
  aiDisabled: 'AI 相似尚未启用，请参阅部署说明配置本地整图模型。',
  guide: '部署说明', running: '扫描中', comparing: '正在比较照片', paused: '已暂停', completed: '扫描完成', cancelled: '已取消', failed: '扫描失败',
  failedCount: '分析失败', pause: '暂停', resume: '继续', cancel: '取消扫描',
  recommend: '建议保留', keep: '保留', remove: '移入回收站', select: '选择清理',
  selectOthers: '选择其他副本', review: '检查清理选择', confirm: '确认移入回收站', dismiss: '取消',
  warning: '选中的照片及动态视频将移入回收站。磁盘空间会在永久删除或到期清理后释放。',
  annotations: '这组包含收藏、分享或人物标注。请检查保留项；删除副本不会合并这些记录，照片分享链接会失效。',
  favorite: '有收藏', shared: '有分享', annotated: '有人物标注', live: '动态照片', owner: '所属用户',
  similarity: '相似度', originalBytes: '待清理原图大小', selected: '已选择', photos: '张',
  similarNote: '相似度不是重复概率。请查看原图，确认不同瞬间或动态视频是否需要保留。',
  preferred: '优先保留文件夹', preferredHint: '输入下面显示的文件夹路径（可选）',
  error: '请求失败，请检查服务状态后重试。', busy: '其他维护任务正在运行，请稍后重试。',
  changed: '照片组已变化，请刷新后重新检查。', partial: '部分照片未能清理，请刷新后检查剩余项。',
  done: '已移入回收站', skipped: '部分照片无法确认完整内容，已跳过。', open: '查看原图',
  visual_hash: '画面指纹相近', visual_hash_ai: '画面指纹和 AI 特征相近', local_features: '局部细节匹配', burst: '可能是连拍', identical: '文件内容相同',
};
const en: typeof zh = {
  title: 'Duplicate photos', description: 'Find copies within each owner’s library and compare what to keep.',
  exact: 'Exact copies', perceptual: 'Visually similar', ai: 'AI similar', refresh: 'Refresh', more: 'Load more',
  empty: 'No duplicate or similar photos found.', scanning: 'Scan visual similarities', scanAI: 'Scan AI similarities',
  scanNote: 'Exact copies need no scan. Visual and AI scans save features and skip unchanged photos next time.',
  aiDisabled: 'AI similarity is not enabled. See the deployment guide to configure the local image model.',
  guide: 'Deployment guide', running: 'Scanning', comparing: 'Comparing photos', paused: 'Paused', completed: 'Scan complete', cancelled: 'Cancelled', failed: 'Scan failed',
  failedCount: 'Analysis failures', pause: 'Pause', resume: 'Resume', cancel: 'Cancel scan',
  recommend: 'Suggested keeper', keep: 'Keep', remove: 'Move to trash', select: 'Select for cleanup',
  selectOthers: 'Select other copies', review: 'Review cleanup', confirm: 'Confirm move to trash', dismiss: 'Cancel',
  warning: 'Selected photos and motion videos will move to trash. Space is released after permanent deletion or expiry.',
  annotations: 'This group has favorites, shares or person annotations. Check the keeper: cleanup does not merge these records and photo share links will stop working.',
  favorite: 'Favorited', shared: 'Shared', annotated: 'Person annotations', live: 'Live photo', owner: 'Owner',
  similarity: 'Similarity', originalBytes: 'Selected original image size', selected: 'Selected', photos: 'photos',
  similarNote: 'Similarity is not a duplicate probability. View originals before deciding whether to keep different moments or motion videos.',
  preferred: 'Preferred folder to keep', preferredHint: 'Enter a folder path shown below (optional)',
  error: 'Request failed. Check the service and retry.', busy: 'Another maintenance task is running. Please retry later.',
  changed: 'This group changed. Refresh and review it again.', partial: 'Some photos could not be moved. Refresh to review remaining items.',
  done: 'Moved to trash', skipped: 'Some photos could not be verified and were skipped.', open: 'View original',
  visual_hash: 'Similar image fingerprints', visual_hash_ai: 'Similar fingerprints and AI features', local_features: 'Matching local details', burst: 'Possible burst', identical: 'Identical file contents',
};
export const duplicateStrings = (locale: Locale) => locale === 'zh' ? zh : en;
