import { FormEvent, useEffect, useState } from 'react';
import { LoaderCircle, ShieldCheck, UserRound, RefreshCw } from 'lucide-react';
import type { ApiClient, User } from '../../app/api';

export default function SettingsWorkspace({ api, currentUser }: { api: ApiClient; currentUser: User }) {
  const [users, setUsers] = useState<User[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [newUsername, setNewUsername] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [scanMessage, setScanMessage] = useState<string | null>(null);
  useEffect(() => { if (currentUser.role !== 'admin') return; void api.listUsers().then((response) => setUsers(response.items)).catch(() => setMessage('Only administrators can view family accounts.')); }, [api, currentUser.role]);
  async function toggle(user: User) { setBusy(true); setMessage(null); try { const updated = await api.updateUser(user.id, { is_active: !user.is_active }); setUsers((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Account could not be updated.'); } finally { setBusy(false); } }
  async function remove(user: User) { if (!window.confirm(`Delete ${user.username}? Their photos will be retained.`)) return; setBusy(true); try { await api.deleteUser(user.id); setUsers((current) => current.filter((item) => item.id !== user.id)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Account could not be deleted.'); } finally { setBusy(false); } }
  async function create(event: FormEvent) { event.preventDefault(); if (!newUsername.trim() || !newPassword) return; setBusy(true); try { const user = await api.createUser({ username: newUsername.trim(), password: newPassword, role: 'user' }); setUsers((current) => [...current, user]); setNewUsername(''); setNewPassword(''); } catch (error) { setMessage(error instanceof Error ? error.message : 'Account could not be created.'); } finally { setBusy(false); } }
  async function rescan() { setScanMessage('Scan queued…'); try { await api.startRescan(); } catch { setScanMessage('Scan could not be started.'); } }
  return <section className="settings-workspace" aria-labelledby="settings-title"><div className="workspace-heading"><div><span className="eyebrow">Your account</span><h1 id="settings-title">Settings</h1></div><UserRound size={21} /></div><div className="account-summary"><span className="avatar">{currentUser.username.slice(0, 1).toUpperCase()}</span><div><strong>{currentUser.username}</strong><small>{currentUser.role === 'admin' ? 'Administrator' : 'Family member'}</small></div></div>{currentUser.role === 'admin' && <><div className="settings-section-heading"><h2>Family accounts</h2><span><ShieldCheck size={15} /> Admin access</span></div>{message && <p className="inline-state" role="alert">{message}</p>}<form className="new-user-form" onSubmit={create}><input aria-label="New username" placeholder="Username" value={newUsername} onChange={(event) => setNewUsername(event.target.value)} /><input aria-label="Temporary password" type="password" placeholder="Temporary password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /><button className="button button-secondary" disabled={busy}>Add member</button></form><div className="user-list">{users.map((user) => <div className="user-row" key={user.id}><div><strong>{user.username}</strong><small>{user.role === 'admin' ? 'Administrator' : 'Family member'} · {user.is_active ? 'Active' : 'Disabled'}</small></div><button className="button button-secondary" disabled={busy || user.id === currentUser.id} onClick={() => void toggle(user)}>{user.is_active ? 'Disable' : 'Enable'}</button><button className="text-button" disabled={busy || user.id === currentUser.id} onClick={() => void remove(user)}>Delete</button></div>)}</div><div className="settings-section-heading scan-heading"><h2>Library index</h2><button className="button button-secondary" onClick={() => void rescan()}><RefreshCw size={15} /> Rescan files</button></div>{scanMessage && <p className="inline-state">{scanMessage}</p>}</>}</section>;
}
