import { FormEvent, useEffect, useState } from 'react';
import { LoaderCircle, ShieldCheck, UserRound, RefreshCw } from 'lucide-react';
import { useI18n } from '../../app/I18nProvider';
import type { ApiClient, User } from '../../app/api';

export default function SettingsWorkspace({ api, currentUser }: { api: ApiClient; currentUser: User }) {
  const { t } = useI18n();
  const [users, setUsers] = useState<User[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [newUsername, setNewUsername] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [scanMessage, setScanMessage] = useState<string | null>(null);
  useEffect(() => { if (currentUser.role !== 'admin') return; void api.listUsers().then((response) => setUsers(response.items)).catch(() => setMessage(t('settings.onlyAdmins'))); }, [api, currentUser.role, t]);
  async function toggle(user: User) { setBusy(true); setMessage(null); try { const updated = await api.updateUser(user.id, { is_active: !user.is_active }); setUsers((current) => current.map((item) => item.id === updated.id ? updated : item)); } catch { setMessage(t('settings.accountUpdateFailed')); } finally { setBusy(false); } }
  async function remove(user: User) { if (!window.confirm(t('settings.confirmDelete', { name: user.username }))) return; setBusy(true); try { await api.deleteUser(user.id); setUsers((current) => current.filter((item) => item.id !== user.id)); } catch { setMessage(t('settings.accountDeleteFailed')); } finally { setBusy(false); } }
  async function create(event: FormEvent) { event.preventDefault(); if (!newUsername.trim() || !newPassword) return; setBusy(true); try { const user = await api.createUser({ username: newUsername.trim(), password: newPassword, role: 'user' }); setUsers((current) => [...current, user]); setNewUsername(''); setNewPassword(''); } catch { setMessage(t('settings.accountCreateFailed')); } finally { setBusy(false); } }
  async function rescan() { setScanMessage(t('settings.scanQueued')); try { await api.startRescan(); } catch { setScanMessage(t('settings.scanFailed')); } }
  return <section className="settings-workspace" aria-labelledby="settings-title"><div className="workspace-heading"><div><span className="eyebrow">{t('settings.yourAccount')}</span><h1 id="settings-title">{t('settings.title')}</h1></div><UserRound size={21} /></div><div className="account-summary"><span className="avatar">{currentUser.username.slice(0, 1).toUpperCase()}</span><div><strong>{currentUser.username}</strong><small>{currentUser.role === 'admin' ? t('shell.administrator') : t('shell.familyMember')}</small></div></div>{currentUser.role === 'admin' && <><div className="settings-section-heading"><h2>{t('settings.familyAccounts')}</h2><span><ShieldCheck size={15} /> {t('settings.adminAccess')}</span></div>{message && <p className="inline-state" role="alert">{message}</p>}<form className="new-user-form" onSubmit={create}><input aria-label={t('settings.newUsername')} placeholder={t('settings.newUsername')} value={newUsername} onChange={(event) => setNewUsername(event.target.value)} /><input aria-label={t('settings.temporaryPassword')} type="password" placeholder={t('settings.temporaryPassword')} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /><button className="button button-secondary" disabled={busy}>{t('settings.addMember')}</button></form><div className="user-list">{users.map((user) => <div className="user-row" key={user.id}><div><strong>{user.username}</strong><small>{user.role === 'admin' ? t('shell.administrator') : t('shell.familyMember')} · {user.is_active ? t('settings.active') : t('settings.disabled')}</small></div><button className="button button-secondary" disabled={busy || user.id === currentUser.id} onClick={() => void toggle(user)}>{user.is_active ? t('settings.disable') : t('settings.enable')}</button><button className="text-button" disabled={busy || user.id === currentUser.id} onClick={() => void remove(user)}>{t('settings.delete')}</button></div>)}</div><div className="settings-section-heading scan-heading"><h2>{t('settings.libraryIndex')}</h2><button className="button button-secondary" onClick={() => void rescan()}><RefreshCw size={15} /> {t('settings.rescanFiles')}</button></div>{scanMessage && <p className="inline-state">{scanMessage}</p>}</>}</section>;
}
