export const trashStrings = {
  zh: {
    title: '回收站', intro: '误删的照片和视频可以在到期前恢复。', mine: '我的回收站', all: '所有用户的回收站',
    retention: '新删除的媒体默认保留 {days} 天。', empty: '回收站是空的', refresh: '刷新', more: '加载更多',
    restore: '恢复', purge: '永久删除', clear: '清空回收站', select: '选择', selectAll: '选择本页可恢复项目',
    selected: '已选择 {count} 项', deleted: '删除于', expires: '到期', days: '剩余 {days} 天', due: '已到期，等待清理',
    folder: '原文件夹', processing: '处理中', recovery: '操作未完成，请重试', retry: '重试操作', cancel: '取消',
    restoreTitle: '恢复所选媒体', purgeTitle: '永久删除所选媒体？', clearTitle: '清空当前范围的回收站？',
    purgeWarning: '原文件及动态照片伴随文件将被彻底删除，无法恢复。', clearWarning: '将永久删除当前范围内已移入回收站的媒体，包括未加载的项目。处理中项目会保留。此操作无法撤销。',
    restoreNote: '原照片的独立分享链接不会重新启用。恢复到已分享的文件夹后，媒体会按该文件夹的分享范围重新可见。',
    original: '恢复到各自的原文件夹', choose: '选择其他文件夹', root: '顶层文件夹', up: '返回上级', useFolder: '恢复到此文件夹',
    destination: '恢复目标', rename: '重名时自动改名（不覆盖已有文件）', mixed: '所选媒体属于不同用户，请分别选择其他恢复目录。',
    error: '操作失败，请重试。', loadError: '无法加载回收站，请重试。', partial: '{count} 项未完成，请查看下方原因后重试。',
    completed: '已完成 {count} 项。', emptyDone: '当前范围内可清理的项目已处理。', conflict: '目标已有同名文件，请选择自动改名或其他目录。',
    forbidden: '没有权限，或目标文件夹不属于原所有者。', missing: '媒体或目标文件夹已不存在。',
    maintenance: '另一个维护任务正在运行，请稍后重试。', pending: '文件操作尚未完成，请重试操作或等待后台恢复。',
    changed: '磁盘文件已变化，请先重新扫描。', preview: '预览暂不可用', folderError: '无法加载文件夹，请重试。',
  },
  en: {
    title: 'Trash', intro: 'Restore deleted photos and videos before they expire.', mine: 'My trash', all: 'All users’ trash',
    retention: 'Newly deleted media is kept for {days} days by default.', empty: 'Trash is empty', refresh: 'Refresh', more: 'Load more',
    restore: 'Restore', purge: 'Delete permanently', clear: 'Empty trash', select: 'Select', selectAll: 'Select loaded restorable items',
    selected: '{count} selected', deleted: 'Deleted', expires: 'Expires', days: '{days} days left', due: 'Expired, awaiting cleanup',
    folder: 'Original folder', processing: 'Processing', recovery: 'Operation incomplete. Please retry.', retry: 'Retry operation', cancel: 'Cancel',
    restoreTitle: 'Restore selected media', purgeTitle: 'Permanently delete selected media?', clearTitle: 'Empty trash in this scope?',
    purgeWarning: 'Originals and motion companions will be permanently deleted. This cannot be undone.', clearWarning: 'Permanently deletes trashed media in this scope, including items not loaded yet. Pending operations are retained. This cannot be undone.',
    restoreNote: 'Individual photo links stay revoked. Media restored to a shared folder becomes visible under that folder’s sharing rules again.',
    original: 'Restore to each original folder', choose: 'Choose another folder', root: 'Top-level folders', up: 'Parent folder', useFolder: 'Restore to this folder',
    destination: 'Destination', rename: 'Automatically rename conflicts (never overwrite)', mixed: 'These items belong to different users. Choose alternate destinations separately.',
    error: 'Operation failed. Please retry.', loadError: 'Could not load trash. Please retry.', partial: '{count} items were not completed. Review the reasons below and retry.',
    completed: '{count} items completed.', emptyDone: 'Eligible items in this scope have been processed.', conflict: 'A file with this name exists. Enable automatic renaming or choose another folder.',
    forbidden: 'Access denied, or the destination belongs to a different owner.', missing: 'The media or destination folder no longer exists.',
    maintenance: 'Another maintenance task is running. Please retry later.', pending: 'A file operation is incomplete. Retry it or wait for background recovery.',
    changed: 'The file on disk has changed. Rescan the library first.', preview: 'Preview unavailable', folderError: 'Could not load folders. Please retry.',
  },
};
