import { FormEvent, useEffect, useState } from 'react';
import { LoaderCircle, Share2, X } from 'lucide-react';
import type { ApiClient, Folder, Share, User } from '../../app/api';

export default function SharingWorkspace({ api }: { api: ApiClient }) {
  const [shares, setShares] = useState<Share[]>([]);
  const [folders, setFolders] = useState<Folder[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [folderId, setFolderId] = useState('');
  const [userId, setUserId] = useState('');
  const [permission, setPermission] = useState<'read' | 'write'>('read');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.listShares(), api.listFolders(), api.listUsers().catch(() => ({ items: [] as User[] }))]).then(([shareResponse, folderResponse, userResponse]) => { setShares(shareResponse.items); setFolders(folderResponse.items); setUsers(userResponse.items); }).catch(() => setMessage('Unable to load sharing details.')); }, [api]);
  async function create(event: FormEvent) { event.preventDefault(); if (!folderId || !userId) return; setBusy(true); setMessage(null); try { const share = await api.createShare({ folder_id: folderId, user_id: userId, permission }); setShares((current) => [share, ...current]); } catch (error) { setMessage(error instanceof Error ? error.message : 'Share could not be created.'); } finally { setBusy(false); } }
  async function revoke(id: string) { setBusy(true); try { await api.revokeShare(id); setShares((current) => current.filter((share) => share.id !== id)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Share could not be revoked.'); } finally { setBusy(false); } }
  return <section className="sharing-workspace" aria-labelledby="sharing-title"><div className="workspace-heading"><div><span className="eyebrow">Family access</span><h1 id="sharing-title">Sharing</h1></div><Share2 size={21} /></div><p className="workspace-lede">Shared folders inherit access through their child folders.</p><form className="share-form" onSubmit={create}><select aria-label="Folder to share" value={folderId} onChange={(event) => setFolderId(event.target.value)}><option value="">Choose folder</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><select aria-label="Family member" value={userId} onChange={(event) => setUserId(event.target.value)}><option value="">Choose member</option>{users.map((user) => <option key={user.id} value={user.id}>{user.username}</option>)}</select><select aria-label="Permission" value={permission} onChange={(event) => setPermission(event.target.value as 'read' | 'write')}><option value="read">Can view</option><option value="write">Can edit</option></select><button className="button button-primary" disabled={busy || !folderId || !userId}>Share folder</button></form>{message && <p className="inline-state" role="alert">{message}</p>}<div className="share-list">{shares.length === 0 ? <div className="empty-timeline"><h2>No active shares</h2><p>Choose a folder and family member to invite them.</p></div> : shares.map((share) => <div className="share-row" key={share.id}><span className="folder-icon"><Share2 size={17} /></span><div><strong>{folders.find((folder) => folder.id === share.resource_id)?.name ?? share.resource_id}</strong><small>{users.find((user) => user.id === share.user_id)?.username ?? share.user_id} · {share.permission === 'write' ? 'Can edit' : 'Can view'}</small></div><button className="icon-button" aria-label="Revoke share" disabled={busy} onClick={() => void revoke(share.id)}><X size={17} /></button></div>)}</div></section>;
}
